config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews
  end
  root "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, -> { extending WithUserAssociationExtension },
      dependent: :destroy
  validates :name, length: { minimum: 3 }, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

    end
  end
  def has_reviewed?(restaurant)
    reviewed_restaurants.include?(restaurant)
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user == current_user
      @restaurant.update(restaurant_params)
      redirect_to '/restaurants'
    else
      flash[:notice] = "not your restaurant"
      redirect_to '/restaurants'
    end
  end


  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user == current_user
       @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
      redirect_to '/restaurants'
    else
      flash[:notice] = "not your restaurant"
      redirect_to '/restaurants'
    end
  end
end
  private
def restaurant_params
  params.require(:restaurant).permit(:name, :description)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
      if @review.save
        redirect_to restaurants_path
        else
          if @review.errors[:user]
            redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
          else
            render :new
        end
      end
  end
  def review_params
   params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  if current_user.has_reviewed? @restaurant
    raise "You have already left a review for this restaurant!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <% end %>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Yelp
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    - if user_signed_in?
      = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign in", new_user_session_path
      = link_to "Sign up", new_user_registration_path

  %body
    = notice
    = yield

app/views/restaurants/edit.html.erb
</h1><div class="main">
  <div class="container">
    <%= form_for @restaurant do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_field :description
  = f.submit

app/views/restaurants/index.html.erb
</h1><div class="main">
  <div class="container">
    <h1>Restaurants</h1>
      <% if @restaurants.any? %>
        <% @restaurants.each do |restaurant| %>
          <%= link_to restaurant.name, restaurant_path(restaurant) %>
            <% restaurant.reviews.each do |review| %>
              <br>
                Review for <%=restaurant.name %>: <%= review.thoughts %>
              <br>
            Given rating: <%= review.rating %>*
          <br>
        <% end %>
          <br>
          <% if current_user && restaurant.user == current_user %>
            <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
              <br>
              <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
            <% end %>
            <br>
            <% if current_user %>
            <% unless current_user.has_reviewed?(restaurant) %>
          <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)  %>
          <% end %>
          <% end %>
        <br>
      <% end %>
      <% else %>
      <h1>no restaurants</h1>
      <% end %>
      <br>
    <a href="/restaurants/new">add a restaurant</a>
  </div>
</div>

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    = link_to restaurant.name, restaurant_path(restaurant)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    %p= restaurant.description
    - reviews = restaurant.reviews
    - reviews.each do |review|
      %p= review.rating
      %p= review.thoughts

- else
  %h1 No restaurants yet!

%a(href='restaurants/new') Add a restaurant

app/views/restaurants/new.html.erb
</h1><div class="main">
  <div class="container">
    <% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </section>
    <% end %>
  
      <%= form_for @restaurant do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <%= f.submit %>
      <% end %>

  </div>
</div>

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being save:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message
        
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/show.html.erb
</h1><div class="main">
  <div class="container">
    <p><%= @restaurant.name %></p>
      <br>
    <p><%= @restaurant.description %></p>
  </div>
</div>

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

app/views/reviews/new.html.erb
</h1><div class="main">
  <div class="container">
    <%= form_for [@restaurant, @review] do |f| %>
      <%= f.label :thoughts %>
      <%= f.text_area :thoughts %>
      <%= f.label :rating %>
      <%= f.select :rating, (1..5) %>
      <%= f.submit 'Leave Review' %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'